CommandPack("Roleplay", "CodeMeAPixel", {
    {
        command  = "me",
        format   = "* #name# #message#",
        help     = "Perform a roleplay action",
        usage    = "/me [action]",
        color    = {255, 220, 100},
        range    = 25.0,
        cooldown = 1,
        args     = {{name = "action", help = "The action to perform", type = "string", minLength = 1}},
    },
    {
        command  = "do",
        format   = "** #message# (#name#)",
        help     = "Describe something in the environment",
        usage    = "/do [description]",
        color    = {180, 220, 255},
        range    = 25.0,
        cooldown = 1,
        args     = {{name = "description", help = "What you describe", type = "string", minLength = 1}},
    },
    {
        command  = "ooc",
        format   = "((OOC)) #name#: #message#",
        help     = "Send an out of character message",
        usage    = "/ooc [message]",
        color    = {180, 180, 180},
        cooldown = 3,
        args     = {{name = "message", help = "Your message", type = "string", minLength = 1}},
    },
    {
        command  = "tweet",
        format   = "[Twitter] @#username#: #message#",
        help     = "Post a tweet",
        usage    = "/tweet [message]",
        color    = {29, 161, 242},
        cooldown = 5,
        args     = {{name = "message", help = "Your tweet", type = "string", minLength = 1, maxLength = 280}},
    },
    {
        command  = "911",
        format   = "[911] #message# | Caller: #name#",
        help     = "Call emergency services",
        usage    = "/911 [message]",
        color    = {255, 50, 50},
        cooldown = 10,
        args     = {{name = "message", help = "Your emergency", type = "string", minLength = 1}},
    },
    {
        command  = "low",
        format   = "#name# [low]: #message#",
        help     = "Speak in a low voice (short range)",
        usage    = "/low [message]",
        color    = {200, 200, 150},
        range    = 5.0,
        cooldown = 1,
        args     = {{name = "message", help = "What you say quietly", type = "string", minLength = 1}},
    },
    {
        command  = "shout",
        format   = "#name# shouts: #message#!",
        help     = "Shout loudly (long range)",
        usage    = "/shout [message]",
        color    = {255, 140, 0},
        range    = 75.0,
        cooldown = 3,
        args     = {{name = "message", help = "What you shout", type = "string", minLength = 1}},
    },
})
